sudo: required
language: bash
services:
  - docker
before_script:
  - docker -v
  - docker-compose -v
  - docker-compose build
script:
  - >
    docker-compose run --rm
    -e CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN
    -e GITHUB_GHPAGES_COMMIT_EMAIL=$GITHUB_GHPAGES_COMMIT_EMAIL
    -e GITHUB_GHPAGES_COMMIT_NAME=$GITHUB_GHPAGES_COMMIT_NAME
    -e GITHUB_TOKEN=$GITHUB_TOKEN
    -e GITHUB_REPO=$GITHUB_REPO
    tests-coverage-report
after_success:
  - docker images
  - ./deploy-docs.sh
notifications:
  slack: keboola:hDCSoKFw77r0k7cJ8LkzoK5p
