version: "2"

services:

  dev:
    build: .
    volumes:
      - .:/code
    working_dir: /code
    command: composer ci
    tty: true
    stdin_open: true
    links:
      - openrefine
    environment:
      - OPENREFINE_HOST=openrefine
      - OPENREFINE_PORT=3333

  openrefine:
    build: ./docker/openrefine
    ports:
      - "3333:3333"
    command: /app/OpenRefine-2.6-rc.2/refine -i 0.0.0.0

  tests-coverage-report:
    build: .
    volumes:
      - .:/code
    working_dir: /code
    command: sh -c 'composer ci && composer test-reporter'
    tty: true
    stdin_open: true
    links:
      - openrefine
    environment:
      - OPENREFINE_HOST=openrefine
      - OPENREFINE_PORT=3333
      - CODECLIMATE_REPO_TOKEN

  wait:
    image: waisbrot/wait
    depends_on:
      - openrefine
    environment:
      - TARGETS=openrefine:3333
      - TIMEOUT=120